- hosts: backend
  tasks:
  - name: 'clone rest repository'
    git:
      repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
      dest: /home
      clone: yes
      update: yes
  - name: 'installing maven'
    apt:
      dest: /home/spring-petclinic-rest
      name: maven
      state: present
      update_cache: true
  - name: 'starting up the backend'
    command: ./mvnw spring-boot:run
      dest: /home/spring-petclinic-rest