- hosts: localhost
  tasks:
  - name: 'clone rest repository'
    git:
      repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
      dest: /home/repos
      clone: yes
      update: yes
  - name: 'installing maven'
    apt:
      name: maven
      state: present
      update_cache: true
  - name: 'starting up the backend'
    command: ./mvnw spring-boot:run
    args:
      chdir: '/home/ubuntu/repos'