- hosts: backend
  tasks:
  - name: 'clone rest repository'
    git:
      repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
      dest: /home
      clone: yes
      update: yes
  - name: 'installing maven'
    command: chdir=/home/spring-petclinic-rest
    apt:
      name: maven
      state: present
      update_cache: true
  - name: 'starting up the backend'
    command: chdir=/home/spring-petclinic-rest
    command: ./mvnw spring-boot:run